# ======== Customize Paths =======
image_path: './sampled_data/images/train2017/'
wandb_run: sdv1-5_one-step
wandb_project: object_features
results_folder: experiments
# ======== Data / Logging ========
pck_threshold: 0.1
train_path: './sampled_data/annotations/instances_sample_train2017.json'
flip_timesteps: False
device: "cuda"
# ======= Ours (All Steps) =======
save_timestep: [9, 5, 0]
num_timesteps: 10
# ======== Ours - One-Step =======
# save_timestep: [0]
# num_timesteps: 1
# ======= Training Hparams =======
weight_decay: 1e-4
max_epochs: 100
max_steps_per_epoch: 5
val_every_n_steps: 1
plot_every_n_steps: -1
lr: 1e-4
# ======== Model Hparams =========
projection_dim: 384
# ============== SDv1-5 ==========
model_id: runwayml/stable-diffusion-v1-5
# ============== SDv2-1 ==========
# model_id: stabilityai/stable-diffusion-2-1-base
diffusion_mode: inversion
output_resolution: 64
load_resolution: 512
batch_size: 1
prompt: ""
negative_prompt: ""
guidance_scale: -1